### ISSUE TITLE
missing .gpr file

### ISSUE THREAD

**Issue by GLHowell** [simonjwright/libadalang2xml#2]
This project showed how I can use libadalang. Thanks!

My build failed cause in the gpr file 

**with "config/libadalang2xml_config.gpr"; **

seems to be missing.

**Comment by simonjwright** [comment]
I’ve got into the habit of building with Alire, which regenerates this configuration GPR ~at every opportunity~as required.

Anyway, it’s now in the repo.

Thanks for the report!
